ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "basePrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "extrasPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "liveAdditionsTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;

UPDATE "Booking"
SET "basePrice" = "totalPrice"
WHERE "basePrice" = 0 AND "totalPrice" > 0;
