ALTER TABLE "Feedback" ADD COLUMN IF NOT EXISTS "lastNotifiedAt" TIMESTAMP(3);
ALTER TABLE "Feedback" ADD COLUMN IF NOT EXISTS "lastEmailSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Feedback" ADD COLUMN IF NOT EXISTS "lastWhatsappSent" BOOLEAN NOT NULL DEFAULT false;
